# Generated by Django 5.2.4 on 2025-07-24 16:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_matricula',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Matrícula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('trancado', 'Trancado')], default='ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '(11) 99999-9999'", regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.CharField(default='Coordenador Temporário', max_length=200, verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default='Descrição temporária', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.CharField(default='Indefinida', max_length=50, verbose_name='Duração'),
        ),
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Curso'),
        ),
    ]
